"""agent team

Revision ID: 057ac60df853
Revises: bbe203813e79
Create Date: 2026-10-09 12:43:24.576324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057ac60df853'
down_revision: Union[str, Sequence[str], None] = 'bbe203813e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_team',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['agents.id'], name=op.f('fk_agent_team_lead_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['agents.id'], name=op.f('fk_agent_team_member_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'member_id', name=op.f('pk_agent_team'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_team')
    # ### end Alembic commands ###
