"""shared files

Revision ID: 4c0a616134b3
Revises: ec71b08a73f4
Create Date: 2026-10-08 16:19:48.433763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0a616134b3'
down_revision: Union[str, Sequence[str], None] = 'ec71b08a73f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_shared_files_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_files')),
    sa.UniqueConstraint('owner_id', 'path', name=op.f('uq_shared_files_owner_id'))
    )
    with op.batch_alter_table('shared_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_files_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_files_owner_id'))

    op.drop_table('shared_files')
    # ### end Alembic commands ###
