"""google sign-in

Revision ID: 9f2ac237d018
Revises: 057ac60df853
Create Date: 2026-10-09 16:43:52.576858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2ac237d018'
down_revision: Union[str, Sequence[str], None] = '057ac60df853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_oauth_accounts_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('owner_id', 'provider', 'subject', name=op.f('uq_oauth_accounts_owner_id'))
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('mcp_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('app', sa.String(length=30), nullable=False, server_default=''))  # existing connections: not hosted
        batch_op.create_foreign_key(batch_op.f('fk_mcp_connections_oauth_account_id_oauth_accounts'), 'oauth_accounts', ['oauth_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mcp_connections_oauth_account_id_oauth_accounts'), type_='foreignkey')
        batch_op.drop_column('app')
        batch_op.drop_column('oauth_account_id')

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_owner_id'))

    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
