"""agent building

Revision ID: bbe203813e79
Revises: 4c0a616134b3
Create Date: 2026-10-09 11:57:38.240208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe203813e79'
down_revision: Union[str, Sequence[str], None] = '4c0a616134b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.String(length=20), nullable=False, server_default=''))  # existing agents: auto

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('building')

    # ### end Alembic commands ###
