"""initial tables

Revision ID: ed34df7b7b6a
Revises: 
Create Date: 2026-10-08 07:39:52.117543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed34df7b7b6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('mcp_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('auth_header_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=False),
    sa.Column('server_name', sa.String(length=200), nullable=False),
    sa.Column('server_version', sa.String(length=80), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_mcp_connections_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_connections')),
    sa.UniqueConstraint('owner_id', 'name', name=op.f('uq_mcp_connections_owner_id'))
    )
    with op.batch_alter_table('mcp_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_connections_owner_id'), ['owner_id'], unique=False)

    op.create_table('model_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(length=12), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_model_credentials_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_credentials'))
    )
    with op.batch_alter_table('model_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_credentials_owner_id'), ['owner_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('can_use_public', sa.Boolean(), nullable=False),
    sa.Column('model_credential_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_credential_id'], ['model_credentials.id'], name=op.f('fk_agents_model_credential_id_model_credentials'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_agents_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('owner_id', 'slug', name=op.f('uq_agents_owner_id'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_owner_id'), ['owner_id'], unique=False)

    op.create_table('mcp_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['mcp_connections.id'], name=op.f('fk_mcp_tools_connection_id_mcp_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_tools')),
    sa.UniqueConstraint('connection_id', 'name', name=op.f('uq_mcp_tools_connection_id'))
    )
    with op.batch_alter_table('mcp_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tools_connection_id'), ['connection_id'], unique=False)

    op.create_table('agent_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_files_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_files')),
    sa.UniqueConstraint('agent_id', 'path', name=op.f('uq_agent_files_agent_id'))
    )
    with op.batch_alter_table('agent_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_files_agent_id'), ['agent_id'], unique=False)

    op.create_table('agent_tool_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_tool_grants_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['mcp_connections.id'], name=op.f('fk_agent_tool_grants_connection_id_mcp_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tool_grants')),
    sa.UniqueConstraint('agent_id', 'connection_id', 'tool_name', name=op.f('uq_agent_tool_grants_agent_id'))
    )
    with op.batch_alter_table('agent_tool_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tool_grants_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tool_grants_connection_id'), ['connection_id'], unique=False)

    op.create_table('public_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('allow_agent_use', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_public_shares_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['agent_files.id'], name=op.f('fk_public_shares_file_id_agent_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_public_shares_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_shares'))
    )
    with op.batch_alter_table('public_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_shares_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_shares_owner_id'))

    op.drop_table('public_shares')
    with op.batch_alter_table('agent_tool_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tool_grants_connection_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tool_grants_agent_id'))

    op.drop_table('agent_tool_grants')
    with op.batch_alter_table('agent_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_files_agent_id'))

    op.drop_table('agent_files')
    with op.batch_alter_table('mcp_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tools_connection_id'))

    op.drop_table('mcp_tools')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_owner_id'))

    op.drop_table('agents')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('model_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_credentials_owner_id'))

    op.drop_table('model_credentials')
    with op.batch_alter_table('mcp_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_connections_owner_id'))

    op.drop_table('mcp_connections')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
